<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OpenSilverType>7</OpenSilverType>
    <PublishTrimmed>true</PublishTrimmed>
    <!-- Uncomment to enable AOT compilation when publishing -->
    <!--<RunAOTCompilation>true</RunAOTCompilation>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.0" PrivateAssets="all" />
    <PackageReference Include="OpenSilver.WebAssembly" Version="3.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <DisableImplicitNamespaceImports>True</DisableImplicitNamespaceImports>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\YGO_CMC_Modding_tool\YGO_CMC_Modding_tool.csproj" />
  </ItemGroup>

</Project>
