using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;

namespace YGO_CMC_Modding_tool.ViewModels
{
    public class MonstersListViewModel
    {
        public class MonsterDisplayItem : INotifyPropertyChanged
        {
            public int Index { get; }
            public string BaseName { get; }
            private bool _isDirty;
            public bool IsDirty
            {
                get => _isDirty;
                set
                {
                    if (_isDirty != value)
                    {
                        _isDirty = value;
                        OnPropertyChanged(nameof(IsDirty));
                        OnPropertyChanged(nameof(Display));
                    }
                }
            }
            public string Display => string.Format("{0:D3} {1}{2}", Index, BaseName, IsDirty ? " *" : "");
            public MonsterDisplayItem(int index, string name)
            {
                Index = index;
                BaseName = name;
            }
            public event PropertyChangedEventHandler PropertyChanged;
            private void OnPropertyChanged(string prop) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(prop));
        }

        public static ObservableCollection<string> MonsterNames { get; } = new ObservableCollection<string>
        {
            "Happy Lover",
            "Skelengel",
            "Hoshiningen",
            "Magician of Faith",
            "Time Wizard",
            "Prisman",
            "Weather Control",
            "Genin",
            "Wing Egg Elf",
            "LaMoon",
            "Dark Witch",
            "Lucky Trinket",
            "Seiyaryu",
            "Moon Envoy",
            "Petit Angel",
            "Fairy's Gift",
            "Rogue Doll",
            "Fiend Reflection #2",
            "Guardian of the Throne Room",
            "Ocubeam",
            "Giltia the D. Knight",
            "Mystical Elf",
            "Ancient Elf",
            "Ill Witch",
            "Kaiser Dragon",
            "Luminous Soldier",
            "Skull Guardian",
            "Airknight Parshath",
            "Gyakutenno Megami",
            "Moisture Creature",
            "Blue-Eyes White Dragon",
            "Shining Friendship",
            "Carat Idol",
            "Blue-Eyes Ultimate Dragon",
            "Kuriboh",
            "Feral Imp",
            "Needle Ball",
            "Right Leg of the Forbidden One",
            "Left Leg of the Forbidden One",
            "Right Arm of the Forbidden One",
            "Left Arm of the Forbidden One",
            "Exodia the Forbidden One",
            "Ryu-Kishin",
            "Blast Sphere",
            "Koumori Dragon",
            "Claw Reacher",
            "Skull Stalker",
            "Curse of Dragon",
            "Metal Guardian",
            "Illusionist Faceless Mage",
            "Terra the Terrible",
            "Ryu-Kishin Powered",
            "Pumpking the King of Ghosts",
            "Summoned Skull",
            "Ushi Oni",
            "Zoa",
            "Dark Elf",
            "Dark Magician Girl",
            "Tri-Horned Dragon",
            "Red-Eyes B. Dragon",
            "Pendulum Machine",
            "Slot Machine",
            "Barrel Dragon",
            "Labyrinth Tank",
            "Black Luster Soldier",
            "Dark Magician",
            "B. Skull Dragon",
            "Whiptail Crow",
            "Metalzoa",
            "Red-Eyes Black Metal Dragon",
            "Magician of Black Chaos",
            "Gate Guardian",
            "Summoned Lord Exodia",
            "Fire Reaper",
            "Lord of the Lamp",
            "Firegrass",
            "Jigen Bakudan",
            "Fire Eye",
            "Flame Viper",
            "Hinotama Soul",
            "Mechanical Snail",
            "Little Chimera",
            "Garoozis",
            "Dragon Piper",
            "Flame Manipulator",
            "Darkfire Dragon",
            "La Jinn the Mystical Genie of the Lamp",
            "Megasonic Eye",
            "Blast Juggler",
            "Charubin the Fire Knight",
            "Rigras Leever",
            "Yamadron",
            "Vermillion Sparrow",
            "Fire Kraken",
            "Firewing Pegasus",
            "Flame Cerebrus",
            "Fireyarou",
            "Tactical Warrior",
            "Molten Behemoth",
            "Tyhone #2",
            "Robotic Knight",
            "Crimson Sunbird",
            "Manga Ryu-Ran",
            "Launcher Spider",
            "Flame Swordsman",
            "Ryu-Ran",
            "Meteor B. Dragon",
            "Ooguchi",
            "Psychic Kappa",
            "Arma Knight",
            "Sinister Serpent",
            "Change Slime",
            "Root Water",
            "Great White",
            "Penguin Soldier",
            "Mech Bass",
            "Yado Karu",
            "Jellyfish",
            "White Dolphin",
            "Kappa Avenger",
            "Tongyo",
            "Aqua Snake",
            "Akihiron",
            "Suijin",
            "Gruesome Goo",
            "7 Colored Fish",
            "Man-eating Black Shark",
            "Penguin Knight",
            "Toad Master",
            "Grappler",
            "Krokodilus",
            "Kanikabuto",
            "Fiend Kraken",
            "High Tide Gyojin",
            "Kairyu-Shin",
            "Guardian of the Sea",
            "Serpentine Princess",
            "Hyosube",
            "Aqua Dragon",
            "Flying Penguin",
            "Crab Turtle",
            "Fortress Whale",
            "Catapult Turtle",
            "Serpent Marauder",
            "Haniwa",
            "Torike",
            "Larvas",
            "Dragon Zombie",
            "Anthrosaurus",
            "Meteor Dragon",
            "Giant Soldier of Stone",
            "Mystic Horseman",
            "Battle Ox",
            "Battle Steer",
            "Rock Ogre Grotto #1",
            "Celtic Guardian",
            "Yormungarde",
            "Destroyer Golem",
            "The Statue of Easter Island",
            "Rock Spirit",
            "Crawling Dragon",
            "Mon Larvas",
            "Gazelle the King of Mythical Beasts",
            "King Tiger Wanghu",
            "Hitotsu-Me Giant",
            "Beaver Warrior",
            "Masaki the Legendary Swordsman",
            "Stone D.",
            "Sword Arm of Dragon",
            "Megazowler",
            "Super War-Lion",
            "Panther Warrior",
            "Judge Man",
            "Rabid Horseman",
            "Sengenjin",
            "Performance of Sword",
            "Gaia The Fierce Knight",
            "Millennium Golem",
            "Petit Moth",
            "Leghul",
            "Mushroom Man",
            "Korogashi",
            "Man-Eater Bug",
            "Needle Worm",
            "Man Eater",
            "Arlownay",
            "Sonic Maid",
            "Minar",
            "Kumootoko",
            "Cockroach Knight",
            "Larvae Moth",
            "Gokibore",
            "Hercules Beetle",
            "Kwagar Hercules",
            "Ancient Tree of Enlightenment",
            "Arsenal Bug",
            "Kuwagata Alpha",
            "Spiked Snail",
            "Green Phantom King",
            "Kamakiriman",
            "Giant Flea",
            "Hunter Spider",
            "Bean Soldier",
            "Big Insect",
            "Queen of Autumn Leaves",
            "Dungeon Worm",
            "Rose Spectre of Dunn",
            "Trent",
            "Great Moth",
            "Perfectly Ultimate Great Moth",
            "Javelin Beetle",
            "Dancing Elf",
            "Droll Bird",
            "Petit Dragon",
            "Bladefly",
            "Insect Soldiers of the Sky",
            "Kurama",
            "Baby Dragon",
            "Wicked Dragon with the Ersatz Head",
            "Dark Gray",
            "One-Eyed Shield Dragon",
            "Killer Needle",
            "Faith Bird",
            "Tyhone",
            "Winged Dragon, Guardian of the Fortress 1",
            "Twin-Headed Behemoth",
            "Fairy Dragon",
            "Kazejin",
            "Harpie Lady",
            "Mavelus",
            "Two-Headed King Rex",
            "Lesser Dragon",
            "Winged Dragon, Guardian of the Fortress 2",
            "Crow Goblin",
            "Birdface",
            "Punished Eagle",
            "Sky Dragon",
            "Thousand Dragon",
            "Parrot Dragon",
            "Harpie Lady Sisters",
            "Metal Dragon",
            "Gaia the Dragon Champion",
            "Harpie's Pet Dragon",
            "Steel Scorpion",
            "Kaminarikozou",
            "Mega Thunderball",
            "LaLa Li-oon",
            "Oscillo Hero 2",
            "Bat",
            "Electric Snake",
            "Shovel Crusher",
            "Two-Mouth Darkruler",
            "Patrol Robo",
            "Mechanical Spider",
            "Electric Lizard",
            "Bolt Penguin",
            "Giga-Tech Wolf",
            "Cyber Soldier",
            "Sanga of the Thunder",
            "Akakieisu",
            "Kinetic Soldier",
            "The Immortal of Thunder",
            "Golgoil",
            "Dice Armadillo",
            "Bolt Escargot",
            "Machine Attacker",
            "Giant Mech-Soldier",
            "Gear Golem the Moving Fortress",
            "Steel Ogre Grotto #1",
            "Thunder Dragon",
            "Kaminari Attack",
            "Steel Ogre Grotto #2",
            "Royal Guard",
            "Tripwire Beast",
            "Cyber Saurus",
            "Twin-Headed Thunder Dragon",
            "Machine King"
        };

        public static ObservableCollection<MonsterDisplayItem> MonsterDisplayNames { get; } = new ObservableCollection<MonsterDisplayItem>();

        static MonstersListViewModel()
        {
            for (int i = 0; i < MonsterNames.Count; i++)
            {
                MonsterDisplayNames.Add(new MonsterDisplayItem(i, MonsterNames[i]));
            }
        }

        public static void SetDirtyFlag(int index, bool dirty)
        {
            if (index < 0 || index >= MonsterDisplayNames.Count) return;
            MonsterDisplayNames[index].IsDirty = dirty;
        }

        public static Dictionary<string, byte> _typeMap = new Dictionary<string, byte>()
        {
            { "Symbol",             0 },
            { "Fairy",              1 },
            { "Fiend",              2 },
            { "Zombie",             3 },
            { "Spellcaster",        4 },
            { "Warrior",            5 },
            { "Beast-Warrior",      6 },
            { "Dragon",             7 },
            { "Sea Serpent",        8 },
            { "Dinosaur",           9 },
            { "Machine",           10 },
            { "Rock",              11 },
            { "Reptile",           12 },
            { "Beast",             13 },
            { "Winged Beast",      14 },
            { "Fish",              15 },
            { "Insect",            16 },
            { "Plant",             17 },
            { "Thunder",           18 },
            { "Aqua",              19 },
            { "Pyro",              20 },
        };

        public static Dictionary<string, byte> _patternMap = new Dictionary<string, byte>()
        {
            {"p1",         0xE0 },
            {"p2",         0xE1 },
            {"p3",         0xE2 },
            {"p4",         0xE3 },
            {"s1+p3",      0xE4 },
            {"s1+x3",      0xE9 },
            {"s2",         0xED },
            {"d2",         0xEF },
            {"d3",         0xF0 },
            {"o2",         0xF1 },
            {"o3",         0xF2 },
            {"p3+x3",      0xF3 },
            {"x1",         0xE5 },
            {"x2",         0xE6 },
            {"x3",         0xE7 },
            {"x4",         0xE8 },
            {"l2",         0xEA },
            {"s1",         0xEC },
        };

        public static Dictionary<string, byte> _attributeMap = new Dictionary<string, byte>()
        {
            { "LIGHT",      0 },
            { "DARK",       1 },
            { "FIRE",       2 },
            { "WATER",      3 },
            { "EARTH",      4 },
            { "WIND",       5 },
            { "WOOD",       6 },
            { "THUNDER",    7 },
        };

        public IEnumerable<string> AttributeKeys => _attributeMap.Keys;
        public IEnumerable<string> TypeKeys => _typeMap.Keys;
        public IEnumerable<string> PatternKeys => _patternMap.Keys;

        public long FirstMonsterOffset { get; } = 0x44D080;
        public int MonsterCount { get; } = 277;
    }
}
